export const metadata = {
  title: 'Disclaimer — ToolVexa',
  description: 'Legal disclaimer regarding the use of tools and calculators on ToolVexa.io.',
};

export default function DisclaimerPage() {
  return (
    <div className="container prose">
      <h1>Disclaimer</h1>
      <p><em>Last Updated: October 2025</em></p>

      <h2>1. Informational Purposes Only</h2>
      <p>All calculators, converters, formatting tools, and content provided on <strong>ToolVexa</strong> (toolvexa.com) are meant for educational and informational purposes only. While we do everything in our power to ensure the algorithmic accuracy of our utilities, we cannot guarantee completely flawless results.</p>

      <h2>2. No Professional Advice</h2>
      <p>The calculations and results provided by ToolVexa (such as the GPA Calculator, Age Calculator, or Percentage Calculator) do not constitute professional, financial, or academic advice. If you are calculating critical academic grades, please double-check with your university registrar. If you are counting critical business or legal documents using our Word Counter, please manually verify the final results.</p>
      
      <p>ToolVexa fundamentally rejects any liability for losses, decisions, or damages made as a result of using the information generated by our automated tools.</p>

      <h2>3. Advertisements and External Links</h2>
      <p>In order to keep the site entirely free for all users, ToolVexa displays third-party advertisements via Google AdSense. We do not explicitly endorse the products, services, or claims made within those third-party ads. Clicking on an ad will divert you to a third-party website, for which ToolVexa assumes no responsibility.</p>

      <h2>4. "As Is" Operations</h2>
      <p>We provide all software and server space without any warranty of continuous, uninterrupted up-time. ToolVexa might occasionally experience bugs, down-time, or technical glitches. Your usage of the platform is strictly "As Is."</p>

      <p>If you discover an error with one of our calculations or formatting outputs, please report it via our <a href="/contact">Contact Page</a>.</p>
    </div>
  );
}
